-- MySQL Script generated by MySQL Workbench
-- Wed Feb  8 23:16:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Agro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Agro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Agro` DEFAULT CHARACTER SET utf8 ;
USE `Agro` ;

-- -----------------------------------------------------
-- Table `Agro`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agro`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `DataNacimento` DATE NULL,
  `CPF` VARCHAR(14) NULL,
  `Celular` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Logradouro` VARCHAR(100) NULL,
  `Numero` VARCHAR(45) NULL,
  `Bairro` VARCHAR(100) NULL,
  `Cidade` VARCHAR(100) NULL,
  `Estado` CHAR(2) NULL,
  `Sexo` ENUM('M', 'F') NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
