-- MySQL Script generated by MySQL Workbench
-- Sun Mar  5 18:23:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testedb` DEFAULT CHARACTER SET utf8 ;
USE `testedb` ;

-- -----------------------------------------------------
-- Table `testedb`.`AgroEndereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedb`.`AgroEndereco` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Logradouro` VARCHAR(100) NULL,
  `Numero` VARCHAR(10) NULL,
  `Bairro` VARCHAR(100) NULL,
  `Cidade` VARCHAR(100) NULL,
  `Estado` CHAR(2) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testedb`.`AgroUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedb`.`AgroUsuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `DataNacimento` DATE NULL,
  `CPF` VARCHAR(14) NULL,
  `Celular` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Sexo` ENUM('M', 'F') NULL,
  `EnderecoId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Usuario_Endereco_idx` (`EnderecoId` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Endereco`
    FOREIGN KEY (`EnderecoId`)
    REFERENCES `testedb`.`AgroEndereco` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
